### ISSUE TITLE
absolute velocity

### ISSUE THREAD

**Issue by Patrick-armhub** [ModiaSim/Modia3D.jl#143]
Hi there, are there any ways to access the relative and absolute velocity while the object is simulating? Or can I only access it for plotting?

**Comment by GerhardHippmann** [comment]
Arbitrary online measurements are implemented in [frameMeasurements.jl](https://github.com/ModiaSim/Modia3D.jl/blob/main/src/Composition/frameMeasurements.jl) and are used in force elements, e.g. [Bushing.jl](https://github.com/ModiaSim/Modia3D.jl/blob/main/src/Composition/ForceElements/Bushing.jl). I think the simplest approach would be to modify or copy an existing force element.

**Comment by Patrick-armhub** [comment]
would it still work if the object I'm working with is not a force element but a revolute joint? I noticed that in Rotational.jl model file, there are sensor models which measures the absolute velocity of the flange? Would that work better?

**Comment by GerhardHippmann** [comment]
Yes, you can also use flanges of prismatic and rotational joints, like `speedSensor` in [ServoWithRampAndRevolute.jl](https://github.com/ModiaSim/Modia3D.jl/blob/main/test/Robot/ServoWithRampAndRevolute.jl). But this is rather [Modia](https://github.com/ModiaSim/Modia.jl) stuff and restricted to joint state variables.
