### ISSUE TITLE
DLR Visualization library Community Edition problem with Julia 1.0.1 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by traversaro** [ModiaSim/Modia3D.jl#3]
Trying to use the latest version of `Modia3D` with the DLR Visualization library Community Edition results in the following error: 
~~~
ERROR: InitError: could not load symbol "SimVis_setTextObject":
/home/straversaro/src/DLR-VIZ-NEW/Visualization 1.5 Community Edition/Visualization/Extras/SimVis/linux/SimVisInterface_CommunityEdition.so: undefined symbol: SimVis_setTextObject
Stacktrace:
 [1] dlsym at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Libdl/src/Libdl.jl:55 [inlined]
 [2] (::getfield(Modia3D.DLR_Visualization, Symbol("##SimVis_Renderer#1#2")))(::String, ::Int64, ::Bool, ::Type, ::Tuple{String,String,Bool,Bool}) at /home/straversaro/.julia/packages/Modia3D/5m7xO/src/renderer/DLR_Visualization/renderer.jl:46
 [3] Type at ./none:0 [inlined]
 [4] #CommunityEdition#5 at /home/straversaro/.julia/packages/Modia3D/5m7xO/src/renderer/DLR_Visualization/renderer.jl:67 [inlined]
 [5] Type at /home/straversaro/.julia/packages/Modia3D/5m7xO/src/renderer/DLR_Visualization/renderer.jl:67 [inlined]
 [6] __init__() at /home/straversaro/.julia/packages/Modia3D/5m7xO/src/Modia3D.jl:99
 [7] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:630
 [8] macro expansion at ./logging.jl:312 [inlined]
 [9] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:701
 [10] _require(::Base.PkgId) at ./loading.jl:934
 [11] require(::Base.PkgId) at ./loading.jl:855
 [12] macro expansion at ./logging.jl:311 [inlined]
 [13] require(::Module, ::Symbol) at ./loading.jl:837
during initialization of module Modia3D
~~~
checking with [`nm`](https://sourceware.org/binutils/docs/binutils/nm.html), indeed the `SimVis_setTextObject` symbol  is not included in the library of the Community Edition.

**Comment by MartinOtter** [comment]
Sorry, this should not have occured (if the community edition is used, not supported elements should just be ignored for the animation). This will be fixed in the next days.

**Comment by MartinOtter** [comment]
Fixed with ff0a48593315a3b2ad012d7a6ed1f9a94894ea4e
(its strange, but on Windows no error was raised when using the CommunityEdition; unfortunately, it could not be detected by Travis CL as well, because Travis CL is performed without the DLR visualization library).

**Comment by traversaro** [comment]
Thanks a lot. Even with this fix for some reason the README examples works fine when using `NoRenderer`, but instead the call to `result = ModiaMath.simulate!(simulationModel);` hangs indefinitely when using the DLR_Visualizer Community Edition, but it is possible that it is a problem of my setup.

**Comment by MartinOtter** [comment]
Please, can you give the exact sequence of commands that lead to the problem.

**Comment by traversaro** [comment]
I will try to replicate it on a clean VM to make sure that is not due to my setup over the weekend. 
However, the overall steps were the following, if I remember correctly: 
* Install Julia v1.0.1 on Ubuntu 18.04 
* Install matplotlib with `sudo apt install python-matplotlib python3-matplotlib` (I was not sure which one julia was going to use)
* Install PyPlot with `]add PyPlot`
* Install the DLR Visualization (version 1.5 - Community Edition) and add the line 
`ENV["DLR_VISUALIZATION"] = "/home/straversaro/src/DLR-VIZ-NEW/Visualization 1.5 Community Edition/Visualization/Extras/SimVis"` in `.julia/config/startup.jl` (I wonder if the space in the path could be a problem) 
* Install Modia3D with `]add https://github.com/ModiaSim/Modia3D.jl` 
* Run: 
~~~julia
import ModiaMath
using Modia3D

material1 = Modia3D.Material(color="LightBlue", transparency=0.3);
material2 = Modia3D.Material(color="Red");

@assembly Pendulum(;Lx = 1.0, Ly=0.2*Lx, Lz=0.2*Lx) begin
   world       = Object3D(Modia3D.CoordinateSystem(0.5*Lx))
   beam_frame0 = Object3D(Modia3D.Solid(Modia3D.SolidBeam(Lx,Ly,Lz), "Aluminium", material1))
   beam_frame1 = Object3D(beam_frame0; r=[-Lx/2, 0.0, 0.0])
   cylinder    = Object3D(beam_frame1,Modia3D.Cylinder(Ly/2,1.2*Ly; material=material2))
   revolute    = Modia3D.Revolute(world, beam_frame1)
end;
simulationModel = Modia3D.SimulationModel(Pendulum(Lx=0.8),stopTime=5.0);
~~~
* After defining the model, trying to launch the following command hangs with the Julia process taking 100% of one cpu (everything works fine if the `ENV["DLR_VISUALIZATION"] ` line is removed from the `startup.jl`):
~~~julia
result = ModiaMath.simulate!(simulationModel);
~~~

**Comment by traversaro** [comment]
I found the problem. The `SimVis` executable had no executable permissions. 
~~~bash
chmod +x <path-to-library>/Visualization/Extras/SimVis
~~~
fixed the issue that I was describing before.

**Comment by MartinOtter** [comment]
Thanks for your findings. I have added your suggestion about execution rights to the README.md file.

Just to make sure: Is the animation of Modia3D now working for you?

**Comment by traversaro** [comment]
Yes, the animation is now working.

**Comment by MartinOtter** [comment]
@Thantalos, @GallLeo: Please, check that the distribution of the DLR Visualization library has "executable permissions" for the SimVis executable on Ubuntu. If not, please correct (this might explain the issue above).

**Comment by AndreaNeumayr** [comment]
Under Linux **only** the Community Edition of the DLR Visualization library is working. A limited number of shapes is displayed, further not all shapes are displayed supported by the Community Edition, like Text.
For further information see https://visualization.ltx.de/ 

Due a complete redesign of Modia3D this issue is closed.
