### ISSUE TITLE
Error: dynamics1 not defined on cut joint

### ISSUE THREAD

**Issue by alhirzel** [ModiaSim/Modia3D.jl#9]
When executing the following Julia script, I am getting an error: `dynamics1 not defined` inside `computeCutForcesAndTorques!`. I think this may be because of the presence of the cut joint. I am not sure how to work around this. My intention with the below model is to have a four-bar linkage that will behave like a pendulum (limp swing).

```julia
import ModiaMath
using Modia3D

@assembly ControlArm(; L=800e-3, T=25e-3, W=50e-3) begin
	controlArmMat = Modia3D.Material(color="Blue", transparency=0.1)

	arm = Modia3D.Part(Modia3D.Solid(
	        Modia3D.SolidBox(L, T, W), "Steel", controlArmMat),
	        [ [-L/2, 0, 0],
	          [ L/2, 0, 0] ])
	support = arm.frames[1]
	spindle = arm.frames[2]

	Modia3D.Object3D(support, Modia3D.Cylinder(T, 3W; material=Modia3D.Material(color="Red")))
	Modia3D.Object3D(spindle, Modia3D.Cylinder(1.2T, 1.5W; material=Modia3D.Material(color="Green")))
end

@assembly DoubleWishbone(; support_spacing=300e-3, spindle_height=350e-3, ca_length=800e-3) begin

	# pre-cook the suspension configuration so the joints line up
	theta = asin((support_spacing-spindle_height)/2/ca_length)

	# nodes of support on vehicle
	support_lower = Object3D()
	support_upper = Object3D(support_lower, r=[0, support_spacing, 0])

	# parts
	uca = ControlArm(L=ca_length)
	lca = ControlArm(L=ca_length)
	spindle = ControlArm(L=spindle_height) # temporary

	# support the control arms
	rev1 = Modia3D.Revolute(support_upper, uca.support; phi_start = -theta)
	rev2 = Modia3D.Revolute(support_lower, lca.support; phi_start = theta)

	# bind the spindle
	rev3 = Modia3D.Revolute(uca.spindle, spindle.spindle; phi_start = pi/2+theta)
	rev4 = Modia3D.Revolute(lca.spindle, spindle.support; phi_start = NaN)
end

sopt = Modia3D.SceneOptions(visualizeFrames=true, defaultFrameLength=0.3)
a = DoubleWishbone(sceneOptions = sopt)
Modia3D.visualizeAssembly!(a) # quicker
#sm = Modia3D.SimulationModel(a, stopTime=30.0)
#result = ModiaMath.simulate!(sm)
```

**Comment by alhirzel** [comment]
I need a construct like `RevolutePlanarLoopConstraint` from MultiBody.

**Comment by MartinOtter** [comment]
Modia3D on github is not the latest version. Currently, development is performed internally at DLR. Once we have a stable version again (probably in 1-2 weeks), it is pushed to github. Modia3D is different to Modelica.Mechanics.MultiBody: Detection of kinematic loops and decision whether planar or not planar cut-joint to cut the loop shall be automatically performed. The user should just define a consistent initial configuration.

**Comment by alhirzel** [comment]
Ah got it! As I reviewed how specialized the cut joint handling was, I figured out I was wrong about needing the constraint. Thank you for your work on Modia3D! I will see if this issue is present on the next stable GitHub release.

**Comment by alhirzel** [comment]
@MartinOtter any updated info?

**Comment by MartinOtter** [comment]
@alhirzel: I did not manage to merge our stable, internal Modia3D version to github. At the end, I made "push -f" that is overwriting the github version completely by our internal version. Unfortunately, this seemed to have removed also one or two pull requests from your side and I could not figure out how to recover them. Please, re-submit. A new stable version (0.3.0) of Modia3D was just released (see [release notes](https://github.com/ModiaSim/Modia3D.jl/releases/tag/v0.3.0)). The cut-joints for dynamic simulation are not yet finalized and are therefore not yet in this released version. I expect to include  them probably at the next week-end.

**Comment by GerhardHippmann** [comment]
In the new release v.0.5.0 cut joints are still not supported, but now an according helpful error message is printed. Support for models with closed kinematic loops is planned for a succeeding release.
